name: Build FFmpeg with libx264 and libfdk_aac

on:
  workflow_dispatch:

jobs:
  build-ffmpeg:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake build-essential cmake git-core libtool \
            pkg-config texinfo wget yasm nasm zlib1g-dev \
            libass-dev libfreetype6-dev libvorbis-dev \
            libx264-dev libfdk-aac-dev libmp3lame-dev libopus-dev

      - name: Clone FFmpeg
        run: |
          git clone https://github.com/ffmpeg/ffmpeg.git
          cd ffmpeg
          git checkout release/6.1

      - name: Configure and build FFmpeg
        run: |
          cd ffmpeg
          ./configure \
            --prefix="$HOME/ffmpeg_build" \
            --pkg-config-flags="--static" \
            --extra-cflags="-I$HOME/ffmpeg_build/include" \
            --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
            --extra-libs="-lpthread -lm" \
            --bindir="$HOME/bin" \
            --enable-gpl \
            --enable-nonfree \
            --enable-libx264 \
            --enable-libfdk-aac \
            --enable-libmp3lame \
            --enable-libopus \
            --enable-libass \
            --enable-libfreetype \
            --enable-small

          make -j$(nproc)
          make install

      - name: Archive FFmpeg Binary
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-binary
          path: ~/bin/ffmpeg
