name: Build FFmpeg with H.265

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y \
          build-essential \
          autoconf \
          automake \
          cmake \
          git \
          libtool \
          pkg-config \
          yasm \
          nasm \
          libx264-dev \
          libx265-dev \
          libnuma-dev \
          libvpx-dev \
          libfdk-aac-dev \
          libmp3lame-dev \
          libopus-dev
    
    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install -y --no-progress \
          git \
          cmake \
          yasm \
          nasm \
          msys2
        
    - name: Clone FFmpeg
      run: |
        git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git ffmpeg
        cd ffmpeg
    
    - name: Build FFmpeg (Linux)
      if: runner.os == 'Linux'
      run: |
        cd ffmpeg
        ./configure \
          --enable-gpl \
          --enable-libx264 \
          --enable-libx265 \
          --enable-libvpx \
          --enable-libfdk-aac \
          --enable-libmp3lame \
          --enable-libopus \
          --enable-nonfree
        make -j$(nproc)
        sudo make install
    
    - name: Build FFmpeg (Windows)
      if: runner.os == 'Windows'
      run: |
        cd ffmpeg
        ./configure \
          --toolchain=msvc \
          --enable-gpl \
          --enable-libx264 \
          --enable-libx265 \
          --enable-libvpx \
          --enable-libfdk-aac \
          --enable-libmp3lame \
          --enable-libopus \
          --enable-nonfree
        make -j$(nproc)
        make install
    
    - name: Verify FFmpeg build
      run: |
        ffmpeg -version
        ffmpeg -codecs | grep hevc
        ffmpeg -codecs | grep h265
    
    - name: Archive binaries (Linux)
      if: runner.os == 'Linux'
      run: |
        mkdir -p ffmpeg_build
        cp /usr/local/bin/ffmpeg ffmpeg_build/
        cp /usr/local/bin/ffprobe ffmpeg_build/
        tar -czvf ffmpeg_h265_linux.tar.gz ffmpeg_build/*
    
    - name: Archive binaries (Windows)
      if: runner.os == 'Windows'
      run: |
        mkdir ffmpeg_build
        copy ffmpeg/ffmpeg.exe ffmpeg_build/
        copy ffmpeg/ffprobe.exe ffmpeg_build/
        7z a ffmpeg_h265_windows.zip ffmpeg_build/*
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ffmpeg_h265_${{ runner.os }}
        path: |
          ffmpeg_h265_linux.tar.gz
          ffmpeg_h265_windows.zip
