name: Auto Build & Release FFmpeg (Windows, H.265)

on:
  push:
    branches: [ "main" ]  # Runs on every push to main
  workflow_dispatch:      # Allow manual triggering
  schedule:
    - cron: '0 0 * * *'   # Optional: Daily build (midnight UTC)

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          make
          pkg-config
          diffutils
          nasm
          gcc
          yasm
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-nasm
          mingw-w64-x86_64-x265

    - name: Clone FFmpeg
      run: |
        git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git ffmpeg

    - name: Build FFmpeg (H.265)
      shell: msys2 {0}
      run: |
        cd ffmpeg
        ./configure \
          --toolchain=msvc \
          --arch=x86_64 \
          --enable-shared \
          --enable-gpl \
          --enable-version3 \
          --enable-nonfree \
          --enable-libx265 \
          --prefix=/opt/ffmpeg
        make -j$(nproc)
        make install

    - name: Zip binaries
      run: |
        mkdir -p ffmpeg-dist/bin
        cp -r /opt/ffmpeg/bin/* ffmpeg-dist/bin/
        7z a ffmpeg-h265-win64.zip ./ffmpeg-dist/*

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-h265-windows
        path: ffmpeg-h265-win64.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ffmpeg-h265-windows

    - name: Auto-create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ffmpeg-h265-win64.zip
        generate_release_notes: true
        prerelease: false
