name: Build FFmpeg with H.265 and Release

on:
  workflow_dispatch:
    inputs:
      build_linux:
        description: "Build for Linux"
        type: boolean
        default: true
      build_windows:
        description: "Build for Windows"
        type: boolean
        default: true
      release_tag:
        description: "Release tag (e.g., v1.0.0)"
        type: string
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix_linux: ${{ steps.set-outputs.outputs.matrix_linux }}
      matrix_windows: ${{ steps.set-outputs.outputs.matrix_windows }}
    steps:
      - name: Set up build matrix
        id: set-outputs
        run: |
          if ${{ github.event.inputs.build_linux }}; then
            echo "matrix_linux=ubuntu-latest" >> $GITHUB_OUTPUT
          else
            echo "matrix_linux=" >> $GITHUB_OUTPUT
          fi
          
          if ${{ github.event.inputs.build_windows }}; then
            echo "matrix_windows=windows-latest" >> $GITHUB_OUTPUT
          else
            echo "matrix_windows=" >> $GITHUB_OUTPUT
          fi

  build_linux:
    needs: setup
    if: ${{ needs.setup.outputs.matrix_linux != '' }}
    runs-on: ${{ needs.setup.outputs.matrix_linux }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y \
          build-essential \
          autoconf \
          automake \
          cmake \
          git \
          libtool \
          pkg-config \
          yasm \
          nasm \
          libx264-dev \
          libx265-dev \
          libnuma-dev \
          libvpx-dev \
          libfdk-aac-dev \
          libmp3lame-dev \
          libopus-dev
        
    - name: Clone FFmpeg
      run: |
        git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git ffmpeg
        cd ffmpeg
    
    - name: Build FFmpeg
      run: |
        cd ffmpeg
        ./configure \
          --prefix=/usr/local \
          --enable-gpl \
          --enable-libx264 \
          --enable-libx265 \
          --enable-libvpx \
          --enable-libfdk-aac \
          --enable-libmp3lame \
          --enable-libopus \
          --enable-nonfree
        make -j$(nproc)
        sudo make install
    
    - name: Verify build
      run: |
        ffmpeg -version
        ffmpeg -codecs | grep -i hevc || echo "HEVC codec not found"
        ffmpeg -codecs | grep -i h265 || echo "H265 codec not found"
    
    - name: Package binaries
      run: |
        mkdir -p ffmpeg_build
        cp /usr/local/bin/ffmpeg ffmpeg_build/
        cp /usr/local/bin/ffprobe ffmpeg_build/
        cp /usr/local/bin/ffplay ffmpeg_build/ || true
        tar -czvf ffmpeg_h265_linux.tar.gz ffmpeg_build/*
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ffmpeg_h265_linux
        path: ffmpeg_h265_linux.tar.gz

  build_windows:
    needs: setup
    if: ${{ needs.setup.outputs.matrix_windows != '' }}
    runs-on: ${{ needs.setup.outputs.matrix_windows }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        choco install -y --no-progress \
          git \
          cmake \
          yasm \
          nasm \
          msys2
        
    - name: Clone FFmpeg
      run: |
        git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git ffmpeg
        cd ffmpeg
    
    - name: Build FFmpeg
      run: |
        cd ffmpeg
        ./configure \
          --toolchain=msvc \
          --enable-gpl \
          --enable-libx264 \
          --enable-libx265 \
          --enable-libvpx \
          --enable-libfdk-aac \
          --enable-libmp3lame \
          --enable-libopus \
          --enable-nonfree
        make -j$(nproc)
        make install
    
    - name: Verify build
      run: |
        ffmpeg -version
        ffmpeg -codecs | findstr /i hevc || echo "HEVC codec not found"
        ffmpeg -codecs | findstr /i h265 || echo "H265 codec not found"
    
    - name: Package binaries
      run: |
        mkdir ffmpeg_build
        copy ffmpeg\ffmpeg.exe ffmpeg_build\
        copy ffmpeg\ffprobe.exe ffmpeg_build\
        copy ffmpeg\ffplay.exe ffmpeg_build\ || echo "FFplay not available"
        7z a ffmpeg_h265_windows.zip ffmpeg_build\*
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ffmpeg_h265_windows
        path: ffmpeg_h265_windows.zip

  release:
    needs: 
      - build_linux
      - build_windows
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          name: FFmpeg with H.265 (${{ github.event.inputs.release_tag }})
          body: |
            FFmpeg with H.265/HEVC support
            Built for:
            ${{ needs.setup.outputs.matrix_linux && '- Linux' || '' }}
            ${{ needs.setup.outputs.matrix_windows && '- Windows' || '' }}
            
            Build date: $(date -u +'%Y-%m-%d')
          files: |
            ${{ needs.setup.outputs.matrix_linux && 'artifacts/ffmpeg_h265_linux/ffmpeg_h265_linux.tar.gz' || '' }}
            ${{ needs.setup.outputs.matrix_windows && 'artifacts/ffmpeg_h265_windows/ffmpeg_h265_windows.zip' || '' }}
          draft: false
          prerelease: false
