name: Build FFmpeg with H.265

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Select build target'
        required: true
        type: choice
        options:
          - linux
          - windows
          - both
        default: both

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            target: linux
            artifact_name: ffmpeg-linux
          - os: windows-latest
            target: windows
            artifact_name: ffmpeg-windows
        exclude:
          - os: ubuntu-latest
            when: ${{ github.event.inputs.build_target == 'windows' }}
          - os: windows-latest
            when: ${{ github.event.inputs.build_target == 'linux' }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dependencies (Linux)
        if: matrix.target == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config yasm nasm git curl libx265-dev

      - name: Set up dependencies (Windows)
        if: matrix.target == 'windows'
        run: |
          choco install -y mingw yasm nasm git
          # Install libx265 via vcpkg
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
          ./vcpkg install x265

      - name: Download FFmpeg source
        run: |
          curl -L https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 -o ffmpeg.tar.bz2
          tar -xjf ffmpeg.tar.bz2
          mv ffmpeg-* ffmpeg

      - name: Configure FFmpeg (Linux)
        if: matrix.target == 'linux'
        run: |
          cd ffmpeg
          ./configure --enable-gpl --enable-libx265 --enable-nonfree
          make -j$(nproc)

      - name: Configure FFmpeg (Windows)
        if: matrix.target == 'windows'
        run: |
          cd ffmpeg
          ./configure --enable-gpl --enable-libx265 --enable-nonfree --toolchain=msvc
          make -j4

      - name: Package build
        run: |
          mkdir -p artifacts
          cp ffmpeg/ffmpeg artifacts/
          cd artifacts
          zip -r ${{ matrix.artifact_name }}.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: artifacts/${{ matrix.artifact_name }}.zip

      - name: Create or update release
        if: github.event.inputs.build_target != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: FFmpeg Build with H.265
          draft: false
          prerelease: false
          files: artifacts/${{ matrix.artifact_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
