name: Build FFmpeg for Linux and Windows with Release Upload

on:
  workflow_dispatch:

env:
  RELEASE_TAG: ffmpeg-restream-build

jobs:
  build-linux:
    name: Build FFmpeg on Linux (x86_64)
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake build-essential cmake git-core libtool \
            pkg-config texinfo wget yasm nasm zlib1g-dev \
            libass-dev libfreetype6-dev libvorbis-dev \
            libx264-dev libfdk-aac-dev libmp3lame-dev libopus-dev \
            libssl-dev

      - name: Clone FFmpeg
        run: |
          git clone https://github.com/ffmpeg/ffmpeg.git
          cd ffmpeg
          git checkout release/6.1

      - name: Configure and build FFmpeg
        run: |
          cd ffmpeg
          ./configure \
            --prefix="$HOME/ffmpeg_build" \
            --pkg-config-flags="--static" \
            --extra-cflags="-I$HOME/ffmpeg_build/include" \
            --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
            --extra-libs="-lpthread -lm" \
            --bindir="$HOME/bin" \
            --enable-gpl \
            --enable-nonfree \
            --enable-libx264 \
            --enable-libfdk-aac \
            --enable-libmp3lame \
            --enable-libopus \
            --enable-libass \
            --enable-libfreetype \
            --enable-protocol=http \
            --enable-protocol=https \
            --enable-protocol=rtmp \
            --enable-muxer=flv \
            --enable-demuxer=flv \
            --enable-small
          make -j$(nproc)
          make install
          mv ~/bin/ffmpeg ./ffmpeg-linux-x86_64

      - name: Upload as Artifact (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-linux
          path: ffmpeg/ffmpeg-linux-x86_64

      - name: Upload to GitHub Release (Linux)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: "FFmpeg Restream Build"
          files: ffmpeg/ffmpeg-linux-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: Build FFmpeg on Windows (MSYS2)
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel git yasm nasm
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-ffmpeg
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-SDL2

      - name: Prepare FFmpeg binary
        run: |
          mkdir -p ~/ffmpeg-bin
          cp /mingw64/bin/ffmpeg.exe ~/ffmpeg-bin/ffmpeg-windows-x86_64.exe
          cp /mingw64/bin/ffprobe.exe ~/ffmpeg-bin/ffprobe-windows-x86_64.exe

      - name: Upload as Artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-windows
          path: |
            ~/ffmpeg-bin/ffmpeg-windows-x86_64.exe
            ~/ffmpeg-bin/ffprobe-windows-x86_64.exe

      - name: Upload to GitHub Release (Windows)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: "FFmpeg Restream Build"
          files: |
            ~/ffmpeg-bin/ffmpeg-windows-x86_64.exe
            ~/ffmpeg-bin/ffprobe-windows-x86_64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
